### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Shadowv7** [maugenst/tabletojson#54]
Hello I would like to know how to wait for the site to load and then put it in JSON format because sometimes it gives me an error because the site did not load.

**Comment by maugenst** [comment]
Hi Shadowv7.

By now I do not exactly understand where the problem is. Got itself has no timeout on it's reuest: https://github.com/sindresorhus/got#timeout 
So if your page simply isn't loading it can be either a backend issue or an issue with a poor connection or or or ... 
What I would like you to is to create a pull request where you write a test or an example that faces this problem. 

Thanks, Marius

**Comment by Shadowv7** [comment]
did

**Comment by maugenst** [comment]
removed dependency to got and replaced it with native fetch.
